package me.kryniowesegryderiusz.kgenerators.enums;

public enum Dependency
{
	WORLD_GUARD,
	JETS_MINIONS,
	HOLOGRAPHIC_DISPLAYS,
	SUPERIOR_SKYBLOCK_2,
	BENTO_BOX,
	VAULT_ECONOMY,
	VAULT_PERMISSIONS,
	SLIMEFUN,
	IRIDIUM_SKYBLOCK,
}